name: '{REPO_NAME}'
description: '{DESCRIPTION}'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^9.3.0+1
  bloc_test: ^10.0.0
  flutter_bloc: ^9.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  mockito: ^5.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.14
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
