name: Initialize Repository
on:
  - push

jobs:
  initialize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get parent hash
        run: echo "PARENT_COUNT=$(git rev-parse HEAD^@ | wc -l)" >> $GITHUB_ENV
      - name: Update project files
        if: env.PARENT_COUNT == 0
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          ORGANIZATION=${GITHUB_REPOSITORY%/*}
          DESCRIPTION="${{ github.event.repository.description }}"
          YEAR=$(date +%Y)

          # Android設定の更新
          sed -i "s/{ORGANIZATION}/${ORGANIZATION,,}/g" android/app/build.gradle
          sed -i "s/{REPO_NAME}/$REPO_NAME/g" android/app/build.gradle

          # Flutterプロジェクト設定の更新
          sed -i "s/{REPO_NAME}/$REPO_NAME/g" pubspec.yaml
          sed -i "s/{DESCRIPTION}/$DESCRIPTION/g" pubspec.yaml

          # ドキュメントの更新
          echo -e "$REPO_NAME\n" > README.md
          echo -e "$DESCRIPTION\n" >> README.md

          # LICENSEファイルの更新
          sed -i "s/{YEAR}/$YEAR/g" LICENSE
          sed -i "s/{COPYRIGHT_HOLDER}/$ORGANIZATION/g" LICENSE

      - name: Commit changes
        if: env.PARENT_COUNT == 0
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Initialize repository from template"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
